version: '3'
services:
  backend:
    image: ${BACKEND_IMG:-qnib/plain-influxdb@sha256:562d863843c48700b6d8d84c953ad86080b109c598e488733639c2d5cce7df65}
    environment:
     - INFLUXDB_DATABASES=qcollect
     - INFLUXDB_GRAPHITE_ENABLED=true
    volumes:
     - /opt/influxdb/shared
    ports:
     - 8083:8083
     - 8086:8086
  chronograf:
    image: qnib/plain-chronograf:0.1.3.7@sha256:23cf1696820dc8c2d3dbb9d11388c8465d68d9256dd38ab5a4f1a38adf579128
    ports:
     - 8888:8888
    environment:
     - INFLUXDB_HOST=tasks.backend
  frontend:
    image: ${FRONTEND_IMG:-qnib/plain-grafana4:4.6.1@sha256:cc079b681c73c23c60c8a5b2416e0a61c2c07f3d530837aa8ed98f03ae19bd9c}
    ports:
     - 3000:3000
    environment:
     - INFLUXDB_DB=graphite
     - INFLUXDB_HOST=tasks.backend
  relay:
    image: qnib/plain-carbon-relay-ng:2017-11-06.v2
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    ports:
     - 2003:2003
     - 2004:2004
     - 8081:8081
    environment:
     - CARBON_RELAY_DESTINATION=tasks.backend:2003
     - CARBON_RELAY_INTERNAL_METRICS_TARGET=tasks.backend:2003
